server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/admin/createEmployee/**    #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/admin/deleteEmployeeById/**   #断言,路径相匹配的进行路由


        - id: payment_routh3
          uri: http://localhost:80
          predicates:
            - Path=/admin/getEmployeeById/**   #断言,路径相匹配的进行路由

        - id: payment_routh4
          uri: http://localhost:8001
          predicates:
            - Path=/admin/updateEmployeeById/**   #断言,路径相匹配的进行路由

        - id: payment_routh5
          uri: http://localhost:8001
          predicates:
            - Path=/admin/deleteById/**   #断言,路径相匹配的进行路由


        - id: payment_routh6
          uri: http://localhost:8001
          predicates:
            - Path=/admin/getAllEmployee/**   #断言,路径相匹配的进行路由

        - id: payment_routh7
          uri: http://localhost:8001
          predicates:
            - Path=/admin/register/**   #断言,路径相匹配的进行路由

        - id: payment_routh8
          uri: http://localhost:8001
          predicates:
            - Path=/admin/login/**   #断言,路径相匹配的进行路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
